@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read a single film
GET {{baseUrl}}/films/1


### Read all films 
GET {{baseUrl}}/films/?minimum-duration=200


###

### Récupérer un film dont le titre commence par "In"
GET http://localhost:3000/films/title/In
Content-Type: application/json

###

### Récupérer un film dont le titre commence par "T"
GET http://localhost:3000/films/title/T
Content-Type: application/json



### Sort (Default Asc)
GET http://localhost:3000/films/sort/title
Content-Type: application/json

